### ISSUE TITLE
Update needed to HAA v0.9.2

### ISSUE THREAD

**Issue by drakorqs** [glumb/haa-configurator#5]
Hi! You made a very cool configuration for HHA, thank you!
Do you have any plans to add new accessories further?
@RavenSystem added new accessories, Garage Door and Window Covering.

**Comment by glumb** [comment]
I've just added the garage accessory https://github.com/glumb/haa-configurator/commit/40a187dcd3938ad56a4dea9031ecf76c4e9f9cf1. Adding the other new features is also planned.

**Comment by the1maximus** [comment]
@glumb is there a new link to get to the garage accessory?  I just tried to compile a configuration for a Sonoff SV and can't seem to find the Garage Door Accessory.

**Comment by glumb** [comment]
There is a bug in the GitHub „build for GitHub pages“ script, resulting in the page not being updated. I’ll seeing I can trigger the update manually. 
The other option is to run the configuration  page locally. `git clone`, `npm i`, `npm run serve`

**Comment by glumb** [comment]
Garage is now available. 

For reference: by disabling and enabling ghPages, the page is rebuild. 
This is the issue I was referring to: https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/true/page/2

**Comment by the1maximus** [comment]
Thanks for the reply, I will try it out later today. I‘m a total newb with coding so It definitely takes me longer to figure things out. You’re tool helps simplify the coding for HAA, I have played around with HomeBridge so I got some of the basics down, but HAA completely messes me up. 

Jean-Claude Pirrello
E-Mail: jc.pirrello@icloud.com
Cell: 516.650.2312
