### ISSUE TITLE
Add option for setup mode button

### ISSUE THREAD

**Issue by maslyankov** [glumb/haa-configurator#9]
Add option for setup mode button as one of the devices listed.
 built-in button configure to enter in setup mode when hold it

**Comment by sorriso93** [comment]
same request here. it is not clear to me how to add the setup switch to the configuration using haa-configurator.
many thanks

**Comment by i3laze** [comment]
I feel it's a duplicate for this one (with less clear title):
https://github.com/glumb/haa-configurator/issues/6

Currently I use these setup and update switches for every HAA device:
`{"1":{"s":[{"a":1}]}},{"1":{"s":[{"a":2}]}}`

**Comment by i3laze** [comment]
Actually nowadays I use HAA Manager.app, which can invoke the same, without flooding accessories with extra switch items:
https://apps.apple.com/app/haa-home-manager-for-homekit/id1556105121
